import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header/Header";
import MainPart from "@/components/main/Main";
import Footer from "@/components/footer/Foter";
import UpperFooter from "@/components/footer/UpperFooter";
import Menu from "@/components/menu/Menu";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Rate Punk App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Menu/>
        <MainPart />
        <UpperFooter />
        <Footer />
      </main>
    </>
  );
}
